// KOMOREBI OS - DATA & CONFIGURATION
// Edit this file to change content, scoring, and protocols.

const DEFAULT_CONFIG = {
    // 1. SYSTEM CONSTANTS
    levels: {
        elite: 6500,
        strong: 5000,
        survival: 3500
    },
    maxXP: 9000,

    // 2. KNOWLEDGE BASE (The Library)
    library: {
        mentalModels: [
            { name: "First Principles Thinking", desc: "Reduce problems to fundamental truths, build upward." },
            { name: "Second-Order Thinking", desc: "Consider consequences beyond the immediate." },
            { name: "Inversion", desc: "Think backward: how could this fail? Then avoid it." },
            { name: "Probabilistic Thinking", desc: "Evaluate decisions using likelihoods, not certainties." },
            { name: "Bayesian Updating", desc: "Adjust beliefs in light of new evidence." },
            { name: "Expected Value", desc: "Quantify decisions: outcomes × probabilities." },
            { name: "Circle of Competence", desc: "Operate within your area of true knowledge." },
            { name: "Falsifiability (Popper)", desc: "If it cannot be proven wrong, it’s not knowledge." },
            { name: "Map ≠ Territory", desc: "Symbols are not reality." },
            { name: "Occam’s Razor", desc: "Prefer the simplest explanation that fits the data." },
            { name: "Hanlon’s Razor", desc: "Never attribute to malice what can be explained by stupidity." },
            { name: "Necessity & Sufficiency", desc: "Distinguish causes from catalysts." },
            { name: "Thought Experiments", desc: "Simulate reality to explore principles." },
            { name: "Decision Trees", desc: "Branching paths for multi-stage decisions." },
            { name: "Sensitivity Analysis", desc: "Test assumptions to see what breaks the model." },
            { name: "Kelly Criterion", desc: "Optimal bet sizing under uncertainty." },
            { name: "Barbell Strategy", desc: "Pair extreme safety with high-upside risk." },
            { name: "Anti-fragility (Taleb)", desc: "Seek systems that benefit from disorder." },
            { name: "Via Negativa", desc: "What not to do is often more important than what to do." },
            { name: "Mimetic Desire (Girard)", desc: "We imitate others' desires; conflict follows." },
            { name: "Status Games", desc: "Most ambition is about pecking order. Avoid them." },
            { name: "Envy & Jealousy", desc: "Underrated forces behind irrational decisions." },
            { name: "Social Proof", desc: "We copy others, especially under uncertainty." },
            { name: "Commitment & Consistency Bias", desc: "We stay loyal to past choices, even when wrong." },
            { name: "Confirmation Bias", desc: "We seek agreement, not truth." },
            { name: "Hindsight Bias", desc: "Everything is obvious after it happens." },
            { name: "Survivorship Bias", desc: "We forget the invisible failures." },
            { name: "Narrative Instinct", desc: "Truth gets rewritten as fable." },
            { name: "Do-Something Syndrome", desc: "Action bias overrides logic." },
            { name: "Pavlovian Association", desc: "Emotionally charged cues override reason." },
            { name: "First-Conclusion Bias", desc: "First idea sticks; mind shuts after." },
            { name: "Availability Heuristic", desc: "Recent, vivid = true (but not really)." },
            { name: "Representativeness Heuristic", desc: "Stereotyping based on past patterns." },
            { name: "Base Rate Neglect", desc: "Ignore statistical norms in favor of specifics." },
            { name: "Stress Response Bias", desc: "Fight or flight inhibits reasoning." },
            { name: "Denial & Coping Bias", desc: "The mind evades pain." },
            { name: "Relative Misery Bias", desc: "We benchmark happiness against others." },
            { name: "Fairness Sensitivity", desc: "Morality instinct overrides logic." },
            { name: "Fundamental Attribution Error", desc: "We blame people over context." },
            { name: "OODA Loop (Boyd)", desc: "Observe, Orient, Decide, Act." },
            { name: "Asymmetric Warfare", desc: "Win by not fighting on equal terms." },
            { name: "Two-Front War", desc: "Divided resources = risk." },
            { name: "Mutually Assured Destruction", desc: "Deterrence through symmetry." },
            { name: "Concentration of Force", desc: "Overwhelm by focus." },
            { name: "Deception (Sun Tzu)", desc: "All war is based on misdirection." },
            { name: "Moral Authority", desc: "Legitimacy is power." },
            { name: "Timing and Tempo", desc: "Speed is a weapon." },
            { name: "Seeing the Front", desc: "Eyes on the field, not the map." },
            { name: "The Lindy Effect", desc: "What survives ages, survives longer." },
            { name: "Chunking", desc: "Grouping aids memory and reasoning." },
            { name: "Meta-Learning", desc: "Learn how to learn." },
            { name: "Socratic Method", desc: "Question everything." },
            { name: "Curiosity Instinct", desc: "Innate drive to explore, understand, and innovate." },
            { name: "Language Instinct", desc: "Deep grammar wired into us." },
            { name: "Pareto Principle", desc: "80% of effects come from 20% of causes." },
            { name: "Hyperbolic Discounting", desc: "Preferring small rewards now over big ones later." },
            { name: "Reciprocity", desc: "We feel obligated to return favors." },
            { name: "Scarcity", desc: "We value things more when they are rare." },
            { name: "Authority", desc: "We obey perceived experts." },
            { name: "Liking", desc: "We say yes to those we like." },
            { name: "Framing Effect", desc: "The way you tell it changes what people hear." },
            { name: "Anchoring Effect", desc: "First number heard shapes expectation." },
            { name: "Contrast Principle", desc: "Context changes perceived value." },
            { name: "Truth-by-Repetition", desc: "Familiarity breeds believability." },
            { name: "Moral Credentialing", desc: "Past good acts license current selfish ones." },
            { name: "Opportunity Cost", desc: "Every choice is a trade." },
            { name: "Margin of Safety", desc: "Room for error is your friend." },
            { name: "Mr. Market", desc: "The market is emotional, not rational." },
            { name: "Compounding", desc: "The most powerful force in the universe." },
            { name: "ROIC", desc: "Return on Invested Capital is core of performance." },
            { name: "Capital Allocation", desc: "Intelligent reinvestment trumps earnings." },
            { name: "Cash Flow over Earnings", desc: "Real cash > accounting illusions." },
            { name: "Founder-Led Advantage", desc: "Skin in the game creates alignment." },
            { name: "Spawner Model", desc: "Businesses that create new businesses (e.g. Amazon)." },
            { name: "Network Effects", desc: "Value increases with more users." },
            { name: "Economies of Scale", desc: "Cost per unit drops as volume increases." },
            { name: "Switching Costs", desc: "Lock-in creates value." },
            { name: "Branding", desc: "Intangible asset that allows pricing power." },
            { name: "Cornered Resource", desc: "Exclusive access to a valuable asset." },
            { name: "Counter-Positioning", desc: "New business model that incumbents cannot copy." },
            { name: "Feedback Loops", desc: "Positive amplifies, negative stabilizes." },
            { name: "Equilibrium", desc: "Where systems settle (or not)." },
            { name: "Emergence", desc: "Complex behavior from simple rules." },
            { name: "Bottlenecks", desc: "Throughput limits performance." },
            { name: "Leverage Points", desc: "Small inputs, big outputs." },
            { name: "Redundancy", desc: "Slack = resilience." },
            { name: "Scaling Laws", desc: "Size changes behavior." },
            { name: "Autocatalysis", desc: "Growth feeds on itself." },
            { name: "Power Laws", desc: "Extreme outliers dominate the average." },
            { name: "Phase Transitions", desc: "Tiny shifts trigger massive change." },
            { name: "Inertia", desc: "Things in motion stay in motion." },
            { name: "Entropy", desc: "Systems tend toward disorder." },
            { name: "Critical Mass", desc: "Threshold effects ignite change." },
            { name: "Thermodynamics", desc: "Conservation, entropy, energy transfer." },
            { name: "Evolution", desc: "Survival via variation and selection." },
            { name: "Fitness Landscapes", desc: "Some solutions are stuck in local optima." },
            { name: "Ecosystem Thinking", desc: "Every part affects the whole." },
            { name: "Activation Energy", desc: "Change requires a spark." },
            { name: "Signal vs. Noise", desc: "Extract meaning from chaos." }
        ],
        productivity: [
            { name: "Growth Mindset (Dweck)", desc: "Believing challenges are a chance to grow, not a threat. The power of 'Yet'." },
            { name: "Re-labeling (Little Bets)", desc: "Fixed mindset sees failure as identity. Growth mindset sees failure as data." },
            { name: "Self-Efficacy Quest (SuperBetter)", desc: "Complete simple daily quests to build confidence for bigger challenges." },
            { name: "Kaizen (Maurer)", desc: "Small, continuous steps to bypass the brain's fear response (Amygdala)." },
            { name: "Compound Effect (Hardy)", desc: "Small, smart choices + consistency + time = radical difference." },
            { name: "Subjective Success (Barker)", desc: "Measure Achievement, Legacy, Significance, and Happiness, not just money." },
            { name: "Optimize for Interesting (Dorie Clark)", desc: "Choose the path that keeps you curious to play the Long Game." },
            { name: "Ego is the Enemy (Holiday)", desc: "Aspiring? Do. Succeeding? Stay humble. Failing? Resilience." },
            { name: "Amor Fati (Holiday)", desc: "Love your fate. Turn obstacles into fuel." },
            { name: "Circle of Control (Stoicism)", desc: "Focus only on what you control. Ignore the rest." },
            { name: "10-10-10 (Suzy Welch)", desc: "How will I feel in 10 mins, 10 months, 10 years?" },
            { name: "The 4 Agreements (Ruiz)", desc: "Be impeccable with your word. Don't take it personally. Don't assume. Do your best." },
            { name: "The ONE Thing (Keller)", desc: "What is the one thing such that by doing it, everything else is easier or unnecessary?" },
            { name: "Essentialism (McKeown)", desc: "Less but better. The disciplined pursuit of less." },
            { name: "The 80/20 Principle (Koch)", desc: "20% of inputs produce 80% of outputs. Focus on the 20%." },
            { name: "Strategic Underachievement (Burkeman)", desc: "Decide in advance what to fail at to save energy for what matters." },
            { name: "Hell Yeah or No (Sivers)", desc: "If it's not a 'Hell Yeah', it's a no." },
            { name: "The Positive No (Ury)", desc: "Yes to values, No to request, Yes to relationship." },
            { name: "Your One Word (Carmichael)", desc: "Find the single value that defines you and use it as a compass." },
            { name: "Pain-Pleasure Association (Robbins)", desc: "Link massive pain to inaction and massive pleasure to action." },
            { name: "Tragic Optimism (Frankl)", desc: "Finding meaning in suffering. The last of the human freedoms." },
            { name: "Psycho-Cybernetics (Maltz)", desc: "Your self-image sets the boundaries of your individual accomplishment." },
            { name: "The Dip (Godin)", desc: "Quit the wrong things fast so you can push through the right Dip." },
            { name: "Grit (Duckworth)", desc: "Passion + Perseverance for long-term goals." },
            { name: "The 40% Rule (Goggins)", desc: "When your mind says you're done, you're only 40% done." },
            { name: "Cookie Jar (Goggins)", desc: "Remember past victories to fuel present struggles." },
            { name: "Winning (Grover)", desc: "Winning demands obsession and doesn't care about your feelings." },
            { name: "Power Laws (Greene)", desc: "Say less. Be audacious. Be formless." },
            { name: "David vs Goliath (Gladwell)", desc: "Neutralize the giant's advantage by changing the rules." },
            { name: "Antifragile (Taleb)", desc: "Gain from disorder. Cap downside, infinite upside." },
            { name: "Subtle Art (Manson)", desc: "Choose what you are willing to suffer for." },
            { name: "Think Like a Monk (Shetty)", desc: "Let go of external expectations. Find your dharma." },
            { name: "Worry Compartmentalization (Carnegie)", desc: "Live in day-tight compartments." },
            { name: "5-4-3-2-1 Grounding (Trenton)", desc: "Engage senses to stop overthinking." },
            { name: "Stress Enhancing Mindset (McGonigal)", desc: "View stress as energy preparation, not a threat." },
            { name: "WRAP Decision Making (Heath)", desc: "Widen options, Reality test, Attain distance, Prepare to be wrong." },
            { name: "Thinking in Bets (Duke)", desc: "Decisions are bets on the future, not certainties." },
            { name: "System 1 vs System 2 (Kahneman)", desc: "Slow down to engage rational thinking over intuition." },
            { name: "Via Negativa (Dobelli)", desc: "Avoid stupidity rather than seeking brilliance." },
            { name: "37% Rule (Algorithms)", desc: "Explore for the first 37%, then exploit the next best option." },
            { name: "First Principles (Elon Musk)", desc: "Boil things down to fundamental truths and reason up." },
            { name: "Second-Order Thinking", desc: "And then what? Look beyond the immediate effect." },
            { name: "Smarter Faster Better (Duhigg)", desc: "Generate motivation by making choices that prove autonomy." },
            { name: "Radical Open-mindedness (Dalio)", desc: "Pain + Reflection = Progress." },
            { name: "Think Again (Grant)", desc: "Think like a scientist, not a preacher, prosecutor, or politician." },
            { name: "Regret Minimization (Pink)", desc: "Foundation, Boldness, Moral, and Connection regrets." },
            { name: "Design Your Life (Burnett/Evans)", desc: "Prototype your life. Don't just plan it." },
            { name: "Code of Extraordinary Mind (Lakhiani)", desc: "Question the 'Brules' (Bullshit Rules) of society." },
            { name: "Born for This (Guillebeau)", desc: "Intersection of Joy, Money, and Flow." },
            { name: "Craftsman Mindset (Newport)", desc: "Be so good they can't ignore you. Passion follows skill." },
            { name: "Mastery (Greene)", desc: "Primal Curiosity + Intense Focus + Mentorship." },
            { name: "Reverse Engineering (Friedman)", desc: "Decode greatness by analyzing the best work." },
            { name: "Talent Hotbeds (Coyle)", desc: "Deep practice + Ignition + Master Coaching." },
            { name: "Range (Epstein)", desc: "Generalists thrive in a specialized world. Sample widely." },
            { name: "Originality (Grant)", desc: "Question the default. Produce volume to find quality." },
            { name: "Giver vs Taker (Grant)", desc: "Givers win in the long run if they avoid burnout." },
            { name: "Win Friends (Carnegie)", desc: "Be genuinely interested in other people." },
            { name: "One Minute Manager", desc: "1 Min Goals, 1 Min Praisings, 1 Min Redirects." },
            { name: "Coaching Habit (Stanier)", desc: "Ask 'What's on your mind?' and 'And what else?'" },
            { name: "Culture Code (Coyle)", desc: "Build safety, share vulnerability, establish purpose." },
            { name: "Good to Great (Collins)", desc: "Hedgehog Concept: Passion, Best at, Economic Engine." },
            { name: "Profit First (Michalowicz)", desc: "Sales - Profit = Expenses. Take profit first." },
            { name: "Start with Why (Sinek)", desc: "People don't buy what you do, they buy why you do it." },
            { name: "StoryBrand (Miller)", desc: "The customer is the hero, not your brand." },
            { name: "E-Myth (Gerber)", desc: "Work ON your business, not IN it. Build systems." },
            { name: "Company of One (Jarvis)", desc: "Better, not bigger. Question growth." },
            { name: "1000 True Fans (Kelly)", desc: "You don't need millions. You need 1000 true fans." },
            { name: "Blue Ocean Strategy", desc: "Don't compete. Create a new market." },
            { name: "Unfair Advantage (Ali/Kubba)", desc: "MILES: Money, Intelligence, Location, Education, Status." },
            { name: "Day One (Bezos)", desc: "Stave off death by maintaining a start-up mentality." },
            { name: "Inside the Box (Boyd)", desc: "Innovation happens by subtraction, division, multiplication." },
            { name: "Jobs to be Done (Christensen)", desc: "Customers hire products to solve a specific problem." },
            { name: "Lean Startup (Ries)", desc: "Build-Measure-Learn. MVP." },
            { name: "Sprint (Google Ventures)", desc: "Solve big problems in 5 days." },
            { name: "Perennial Seller (Holiday)", desc: "Make something timeless. Play the long game." },
            { name: "To Sell Is Human (Pink)", desc: "Attunement, Buoyancy, Clarity." },
            { name: "Influence (Cialdini)", desc: "Reciprocity, Commitment, Social Proof, Authority, Liking, Scarcity." },
            { name: "Magic Words (Jones)", desc: "'Just imagine', 'How open-minded are you?'" },
            { name: "5 Second Rule (Robbins)", desc: "Count 5-4-3-2-1-GO to bypass hesitation." },
            { name: "Eat That Frog (Tracy)", desc: "Do the biggest, ugliest task first thing." },
            { name: "2-Minute Rule (Clear)", desc: "If it takes < 2 mins, do it now." },
            { name: "Time Boxing (Eyal)", desc: "Schedule every minute of your day." },
            { name: "WOOP (Oettingen)", desc: "Wish, Outcome, Obstacle, Plan." },
            { name: "Ivy Lee Method", desc: "Define your 3 & 1 priorities the night before." },
            { name: "Reversal of Desire (The Tools)", desc: "Scream 'Bring it on!' when facing pain." },
            { name: "Intermittent Sobriety (Lembke)", desc: "Abstain from high-dopamine inputs to reset." },
            { name: "Batching Buckets (Allen)", desc: "Group similar tasks to reduce context switching." },
            { name: "Pomodoro Technique", desc: "25 min focus, 5 min diffuse mode." },
            { name: "Checklist Manifesto (Gawande)", desc: "Use checklists to prevent stupid mistakes." },
            { name: "Deep Work (Newport)", desc: "Dedicate blocks of time to distraction-free cognitive work." },
            { name: "Flow (Csikszentmihalyi)", desc: "Balance challenge and skill to enter the zone." },
            { name: "The One Thing (Keller)", desc: "What is the one thing that makes everything else easier?" },
            { name: "Tiny Habits (Fogg)", desc: "Anchor a tiny behavior to an existing trigger." },
            { name: "Bullet Journal (Carroll)", desc: "Rapid logging of tasks, events, and notes." },
            { name: "Second Brain (Forte)", desc: "CODE: Capture, Organize, Distill, Express." },
            { name: "Zettelkasten (Ahrens)", desc: "Smart notes. Connect ideas to build a web of knowledge." },
            { name: "12 Week Year (Moran)", desc: "Create urgency by shrinking your timeline." },
            { name: "4 Disciplines of Execution", desc: "Focus on the WIG (Wildly Important Goal)." },
            { name: "When (Pink)", desc: "Match your chronotype to your tasks." },
            { name: "Effortless (McKeown)", desc: "Make it easy to do what matters." }
        ],
        investors: [
            { name: "Stanley Druckenmiller", resource: "The Genius of Stan Druckenmiller (MOI Global)", years: "30 Years" },
            { name: "Mark Leonard", resource: "Constellation Shareholder Letters / Q&A", years: "25 Years" },
            { name: "Warren Buffett", resource: "Berkshire Shareholder Letters (1965-2023)", years: "55 Years" },
            { name: "Charlie Munger", resource: "Poor Charlie's Almanack & Transcripts", years: "15+ Years" },
            { name: "Seth Klarman", resource: "Margin of Safety & Baupost Letters", years: "25 Years" },
            { name: "Rakesh Jhunjhunwala", resource: "The Big Bull of India (Insights & PDFs)", years: "35 Years" },
            { name: "Peter Lynch", resource: "One Up on Wall Street", years: "15 Years" },
            { name: "Nick Sleep", resource: "Nomad Investment Partnership Letters", years: "13 Years" },
            { name: "Li Lu", resource: "Himalayan Capital / Modernization", years: "20+ Years" },
            { name: "Howard Marks", resource: "The Most Important Thing / Memos", years: "25+ Years" },
            { name: "Joel Greenblatt", resource: "The Little Book that Beats the Market / Class Notes", years: "20 Years" },
            { name: "George Soros", resource: "The Alchemy of Finance", years: "35 Years" },
            { name: "Benjamin Graham", resource: "The Intelligent Investor / Security Analysis", years: "25 Years" },
            { name: "Philip Fisher", resource: "Common Stocks and Uncommon Profits", years: "70 Years" },
            { name: "Terry Smith", resource: "Investing for Growth / Fundsmith Letters", years: "20+ Years" },
            { name: "Bill Ackman", resource: "Pershing Square Letters & Activist Campaigns", years: "20 Years" },
            { name: "Chuck Akre", resource: "Akre Capital Management Letters (The Three-Legged Stool)", years: "30 Years" },
            { name: "John Templeton", resource: "Templeton Growth Fund", years: "40 Years" },
            { name: "Walter Schloss", resource: "Factors Needed to Make Money in the Stock Market", years: "50 Years" },
            { name: "Mohnish Pabrai", resource: "The Dhandho Investor", years: "20 Years" },
            { name: "Michael Mauboussin", resource: "More Than You Know / Consilient Observer", years: "Strategy" },
            { name: "Ray Dalio", resource: "Principles / Bridgewater Daily Observations", years: "40 Years" },
            { name: "Jamie Dimon", resource: "JPMorgan Chase Shareholder Letters", years: "20 Years" },
            { name: "Bruce Greenwald", resource: "Class Notes & Value Investing: From Graham to Buffett", years: "Academic" },
            { name: "Jim Rogers", resource: "Investment Biker", years: "20 Years" },
            { name: "Rick Guerin", resource: "Pacific Partners", years: "20 Years" },
            { name: "David Tepper", resource: "Appaloosa Management", years: "20 Years" },
            { name: "Kevin Daly", resource: "FiveT Capital", years: "15 Years" },
            { name: "Eddie Lampert", resource: "ESL Investments", years: "20 Years" },
            { name: "David Einhorn", resource: "Greenlight Capital / Fooling Some of the People All of the Time", years: "20 Years" },
            { name: "Stan Perlmeter", resource: "Perlmeter Investments", years: "20 Years" },
            { name: "Daniel Loeb", resource: "Third Point Letters", years: "20 Years" },
            { name: "Tom Knapp", resource: "Tweedy, Browne", years: "20 Years" },
            { name: "Shelby Davis", resource: "Davis Dynasty", years: "45 Years" },
            { name: "Bruce Berkowitz", resource: "Fairholme Fund", years: "15 Years" },
            { name: "Julian Robertson", resource: "Tiger Management", years: "20 Years" },
            { name: "Lou Simpson", resource: "GEICO Investments", years: "25 Years" },
            { name: "Prem Watsa", resource: "Fairfax Financial Letters", years: "25 Years" },
            { name: "Robert Rodriguez", resource: "FPA Capital", years: "30 Years" },
            { name: "John Neff", resource: "Vanguard Windsor Fund", years: "35 Years" },
            { name: "Glenn Greenberg", resource: "Chieftain Capital", years: "25 Years" },
            { name: "Bill Ruane", resource: "Sequoia Fund", years: "15 Years" },
            { name: "Philip Carret", resource: "Pioneer Fund", years: "55 Years" },
            { name: "Adam Smith", resource: "The Wealth of Nations", years: "Classic" },
            { name: "John Brooks", resource: "Business Adventures", years: "Classic" },
            { name: "Robert Pirsig", resource: "Zen and the Art of Motorcycle Maintenance", years: "Philosophy" },
            { name: "Josh Waitzkin", resource: "The Art of Learning", years: "Performance" },
            { name: "Hamilton Helmer", resource: "7 Powers", years: "Strategy" },
            { name: "William Thorndike", resource: "The Outsiders", years: "Capital Allocation" },
            { name: "Lawrence Cunningham", resource: "Quality Investing / Margin of Trust", years: "Analysis" },
            { name: "Jeremy Miller", resource: "Warren Buffett's Ground Rules", years: "History" },
            { name: "Lee Freeman-Shor", resource: "The Art of Execution", years: "Process" },
            { name: "Brad Feld", resource: "Venture Deals", years: "VC" },
            { name: "Tren Griffin", resource: "Charlie Munger: The Complete Investor", years: "Wisdom" },
            { name: "William Green", resource: "Richer, Wiser, Happier", years: "Wisdom" },
            { name: "Glen Arnold", resource: "The Deals of Warren Buffett", years: "History" },
            { name: "Mary Buffett", resource: "Buffettology", years: "Analysis" },
            { name: "Alice Schroeder", resource: "The Snowball", years: "Biography" },
            { name: "Peter Kaufman", resource: "Poor Charlie's Almanack", years: "Multidisciplinary" }
        ],
        quotes: [
            "“Discipline equals freedom.” — Jocko Willink",
            "“The impediment to action advances action.” — Marcus Aurelius",
            "“You do not rise to the level of your goals. You fall to the level of your systems.” — James Clear",
            "“The score takes care of itself.” — Bill Walsh",
            "“He who has a why to live can bear almost any how.” — Nietzsche",
            "“Be the person with embarrassing goals and impressive results.” — Stephen Guise",
            "“Action isn't just the effect of motivation; it's also the cause of it.” — Mark Manson",
            "“Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.” — Archimedes",
            "“What you do is what matters, not what you think or say or plan.” — Jason Fried",
            "“It is the quality of time at work that counts and the quantity of time at home that matters.” — Brian Tracy",
            "“I am the master of my fate, I am the captain of my soul.” — Invictus",
            "“We suffer more in imagination than in reality.” — Seneca",
            "“If you want to go fast, go alone. If you want to go far, go together.” — African Proverb",
            "“It is not the critic who counts... The credit belongs to the man who is actually in the arena.” — Theodore Roosevelt",
            "“Everything in life is a mind game!” — David Goggins",
            "“Slow is smooth, smooth is fast.” — Navy SEALs",
            "“Invert, always invert.” — Jacobi",
            "“I want to be able to look back and say, ‘I didn’t solve everything, but I didn’t create any new problems.’” — Naval Ravikant",
            "“Spend each day trying to be a little wiser than you were when you woke up.” — Charlie Munger",
            "“To get what you want, you have to deserve what you want.” — Charlie Munger",
            "“Compound interest is the eighth wonder of the world. He who understands it, earns it ... he who doesn't ... pays it.” — Einstein",
            "“I never allow myself to hold an opinion on anything that I don't know the other side's argument better than they do.” — Charlie Munger",
            "“The best revenge is not to be like your enemy.” — Marcus Aurelius",
            "“Waste no more time arguing about what a good man should be. Be one.” — Marcus Aurelius",
            "“If you are going through hell, keep going.” — Winston Churchill",
            "“Whether you think you can, or you think you can't – you're right.” — Henry Ford",
            "“The only way to do great work is to love what you do.” — Steve Jobs",
            "“It does not matter how slowly you go as long as you do not stop.” — Confucius",
            "“Simplicity is the ultimate sophistication.” — Leonardo da Vinci",
            "“Knowing yourself is the beginning of all wisdom.” — Aristotle",
            "“Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.” — Marcus Aurelius",
            "“Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea.” — Swami Vivekananda",
            "“You have to grow from the inside out. None can teach you, none can make you spiritual.” — Swami Vivekananda",
            "“In a conflict between the heart and the brain, follow your heart.” — Swami Vivekananda",
            "“The world is nothing but change. Our life is perception.” — Marcus Aurelius",
            "“Man is affected not by events but by the view he takes of them.” — Epictetus",
            "“Throw me to the wolves and I will return leading the pack.” — Seneca",
            "“The best armour of old age is a well spent life preceding it.” — Charlie Munger",
            "“Comfort is no test of truth. Truth is often far from being comfortable.” — Swami Vivekananda",
            "“If I change, the world will change, no-one else will change the world for me.” — Unknown"
        ]
    },

    // 3. PROTOCOL DEFINITIONS (The Checkboxes)
    protocols: [
        {
            id: "health",
            title: "Health",
            columns: 3,
            cards: [
                {
                    id: "supplements",
                    title: "Supplement Stack",
                    maxXP: 500,
                    items: [
                        { id: "supplementStack", label: "Stack complete", xp: 500 }
                    ]
                },
                {
                    id: "smoothie",
                    title: "Supersmoothie",
                    maxXP: 500,
                    items: [
                        { id: "smoothie", label: "Smoothie complete", xp: 500 }
                    ]
                },
                {
                    id: "fitness",
                    title: "Fitness & Recovery",
                    maxXP: 1000,
                    scoringType: "count_multiplier", 
                    perItemXP: 334,
                    items: [
                        { id: "sunshine", label: "Sunshine" },
                        { id: "rollerYoga", label: "Roller / Yoga" },
                        { id: "protein120", label: "Protein ≥ 120g" },
                        { id: "exercise", label: "Exercise" },
                        { id: "cold", label: "Cold / sauna" }
                    ]
                }
            ]
        },
        {
            id: "mind",
            title: "Mind & Arete",
            columns: 3,
            cards: [
                {
                    id: "wisdom",
                    title: "Wisdom & Clarity",
                    maxXP: 1000,
                    scoringType: "count_multiplier",
                    perItemXP: 250,
                    items: [
                        { id: "gratitude", label: "Gratitude" },
                        { id: "journal", label: "Journal" },
                        { id: "meditate", label: "Meditate" },
                        { id: "mentalModel", label: "Mental model" },
                        { id: "productivityGame", label: "Productivity game" },
                        { id: "philosophy", label: "Philosophy" }
                    ]
                },
                {
                    id: "arete",
                    title: "Arete & Alignment",
                    maxXP: 1000,
                    scoringType: "count_multiplier",
                    perItemXP: 500,
                    items: [
                        { id: "familyTime", label: "Family time" },
                        { id: "golf", label: "Hit balls / play 9" },
                        { id: "fiction", label: "Read sci-fi / fiction" },
                        { id: "lunchDinner", label: "Lunch or dinner out" },
                        { id: "contribution", label: "Contribution" }
                    ]
                },
                {
                    id: "values",
                    title: "Values",
                    maxXP: 1000,
                    scoringType: "count_multiplier",
                    perItemXP: 334,
                    items: [
                        { id: "valueCourage", label: "Courage" },
                        { id: "valueAdventure", label: "Adventure" },
                        { id: "valueSelfImprovement", label: "Self-improvement" },
                        { id: "valueIntegrity", label: "Integrity" },
                        { id: "valueDiscipline", label: "Discipline" },
                        { id: "valueKindness", label: "Kindness" }
                    ]
                }
            ]
        },
        {
            id: "craft",
            title: "Craft & Duty",
            columns: 2,
            cards: [
                {
                    id: "mastery",
                    title: "Mastery",
                    maxXP: 2000,
                    scoringType: "count_multiplier",
                    perItemXP: 666,
                    items: [
                        { id: "investingReading", label: "Investing reading list" },
                        { id: "researchMemo", label: "Research memo" },
                        { id: "investorInteraction", label: "Investor interaction" }
                    ]
                },
                {
                    id: "responsibility",
                    title: "Responsibility",
                    maxXP: 2000,
                    scoringType: "count_multiplier",
                    perItemXP: 666,
                    items: [
                        { id: "earnIncome", label: "Earn income" },
                        { id: "completeTaxes", label: "Complete taxes / admin" },
                        { id: "hectorBellaEducation", label: "Hector & Bella education" }
                    ]
                }
            ]
        }
    ],
    
    // 4. DAILY WORKOUTS (Editable via UI)
    workouts: [
        { t: "Sunday", d: "Endurance/Cardio (Swim, Hike, Long Zone 2)" },
        { t: "Monday", d: "Lower Body Strength (Squat/Deadlift, Posterior Chain)" },
        { t: "Tuesday", d: "Sauna + Cold Exposure (3-5 Rounds)" },
        { t: "Wednesday", d: "Upper Body Strength (Push/Pull, Delts)" },
        { t: "Thursday", d: "Cardio Endurance (Row/Ski/Run/Bike/Ruck)" },
        { t: "Friday", d: "HIIT (Bike, Row, Sled, KB Swings - No Burpees)" },
        { t: "Saturday", d: "Hypertrophy (Arms, Core, Calves, Neck)" }
    ]
};
